name: {{project-name}}
description: {{description}}
author: {{authors}}
inputs:
  error:
    description: 'The error message to display, if any'
    required: false
    default: ''
outputs:
  error:
    description: 'The description of any error that occurred'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/{{github_org}}/{{github_repo}}:v1'
  args:
    - {% raw %}${{ inputs.error }}{% endraw %}
